import Head from "next/head";
import Image from "next/image";
import { Navbar, Breadcrumbs, Footer, MainContent } from "../components";
import styles from "../styles/Home.module.css";

// main page image
// https://upload.wikimedia.org/wikipedia/commons/6/63/Havelock%2C_Andaman_%26_Nicobar_Islands.JPG

export default function Home() {
  return (
    <div className={styles.container}>
      <Navbar />
      <Head>
        <title>Ass NextJS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Breadcrumbs />
        <div className={styles.mainImageSection}>
          <div className={styles.mainBackgroundImage}></div>
          <div className={styles.mainImagetext}>
            <h1>Havelock Island</h1>
            <p>
              Travel Guide - Top Things to Do & See, Hotel & Resorts,
              Restaurants & Cafe and more
            </p>
          </div>
        </div>
        <MainContent />
      </main>

      {/* <Footer /> */}
    </div>
  );
}
